system:
  mode: "historical"
  random_seed: 123
  num_parallel_envs: 1
  log_level: "INFO"

data:
  historical:
    data_path: "data/cleaned_macro_df_with_BTC_last_10000_mins.csv"
    train_test_split: 0.99
    price_column: close_BTC
    atr_column: atr_15m_BTC
    feature_columns:
      - open_BTC
      - high_BTC
      - low_BTC
      - close_BTC
      - v_BTC
      - open_ES
      - high_ES
      - low_ES
      - close_ES
      - v_ES
      - open_VX
      - high_VX
      - low_VX
      - close_VX
      - v_VX
      - open_CL
      - high_CL
      - low_CL
      - close_CL
      - v_CL
      - open_GC
      - high_GC
      - low_GC
      - close_GC
      - v_GC
      - open_ZN
      - high_ZN
      - low_ZN
      - close_ZN
      - v_ZN
      - open_DX
      - high_DX
      - low_DX
      - close_DX
      - v_DX
      - sma_20_1mBTC
      - sma_20_15mBTC
      - sma_20_60mBTC
      - rsi_1m_BTC
      - tsi_1m_BTC
      - ultimate_osc_1m_BTC
      - williams_r_1m_BTC
      - adx_1m_BTC
      - adx_pos_1m_BTC
      - adx_neg_1m_BTC
      - mass_index_1m_BTC
      - macd_1m_BTC
      - macd_diff_1m_BTC
      - macd_signal_1m_BTC
      - atr_1m_BTC
      - bb_bbm_1m_BTC
      - bb_bbh_1m_BTC
      - bb_bbhi_1m_BTC
      - bb_bbl_1m_BTC
      - bb_bbli_1m_BTC
      - rsi_15m_BTC
      - tsi_15m_BTC
      - ultimate_osc_15m_BTC
      - williams_r_15m_BTC
      - adx_15m_BTC
      - adx_pos_15m_BTC
      - adx_neg_15m_BTC
      - mass_index_15m_BTC
      - macd_15m_BTC
      - macd_diff_15m_BTC
      - macd_signal_15m_BTC
      - atr_15m_BTC
      - bb_bbm_15m_BTC
      - bb_bbh_15m_BTC
      - bb_bbhi_15m_BTC
      - bb_bbl_15m_BTC
      - bb_bbli_15m_BTC
      - rsi_60m_BTC
      - tsi_60m_BTC
      - ultimate_osc_60m_BTC
      - williams_r_60m_BTC
      - adx_60m_BTC
      - adx_pos_60m_BTC
      - adx_neg_60m_BTC
      - mass_index_60m_BTC
      - macd_60m_BTC
      - macd_diff_60m_BTC
      - macd_signal_60m_BTC
      - atr_60m_BTC
      - bb_bbm_60m_BTC
      - bb_bbh_60m_BTC
      - bb_bbhi_60m_BTC
      - bb_bbl_60m_BTC
      - bb_bbli_60m_BTC
      - sma_20_1mES
      - sma_20_15mES
      - sma_20_60mES
      - rsi_1m_ES
      - tsi_1m_ES
      - ultimate_osc_1m_ES
      - williams_r_1m_ES
      - adx_1m_ES
      - adx_pos_1m_ES
      - adx_neg_1m_ES
      - mass_index_1m_ES
      - macd_1m_ES
      - macd_diff_1m_ES
      - macd_signal_1m_ES
      - atr_1m_ES
      - bb_bbm_1m_ES
      - bb_bbh_1m_ES
      - bb_bbhi_1m_ES
      - bb_bbl_1m_ES
      - bb_bbli_1m_ES
      - rsi_15m_ES
      - tsi_15m_ES
      - ultimate_osc_15m_ES
      - williams_r_15m_ES
      - adx_15m_ES
      - adx_pos_15m_ES
      - adx_neg_15m_ES
      - mass_index_15m_ES
      - macd_15m_ES
      - macd_diff_15m_ES
      - macd_signal_15m_ES
      - atr_15m_ES
      - bb_bbm_15m_ES
      - bb_bbh_15m_ES
      - bb_bbhi_15m_ES
      - bb_bbl_15m_ES
      - bb_bbli_15m_ES
      - rsi_60m_ES
      - tsi_60m_ES
      - ultimate_osc_60m_ES
      - williams_r_60m_ES
      - adx_60m_ES
      - adx_pos_60m_ES
      - adx_neg_60m_ES
      - mass_index_60m_ES
      - macd_60m_ES
      - macd_diff_60m_ES
      - macd_signal_60m_ES
      - atr_60m_ES
      - bb_bbm_60m_ES
      - bb_bbh_60m_ES
      - bb_bbhi_60m_ES
      - bb_bbl_60m_ES
      - bb_bbli_60m_ES
      - sma_20_1mVX
      - sma_20_15mVX
      - sma_20_60mVX
      - rsi_1m_VX
      - tsi_1m_VX
      - ultimate_osc_1m_VX
      - williams_r_1m_VX
      - adx_1m_VX
      - adx_pos_1m_VX
      - adx_neg_1m_VX
      - mass_index_1m_VX
      - macd_1m_VX
      - macd_diff_1m_VX
      - macd_signal_1m_VX
      - atr_1m_VX
      - bb_bbm_1m_VX
      - bb_bbh_1m_VX
      - bb_bbhi_1m_VX
      - bb_bbl_1m_VX
      - bb_bbli_1m_VX
      - rsi_15m_VX
      - tsi_15m_VX
      - ultimate_osc_15m_VX
      - williams_r_15m_VX
      - adx_15m_VX
      - adx_pos_15m_VX
      - adx_neg_15m_VX
      - mass_index_15m_VX
      - macd_15m_VX
      - macd_diff_15m_VX
      - macd_signal_15m_VX
      - atr_15m_VX
      - bb_bbm_15m_VX
      - bb_bbh_15m_VX
      - bb_bbhi_15m_VX
      - bb_bbl_15m_VX
      - bb_bbli_15m_VX
      - rsi_60m_VX
      - tsi_60m_VX
      - ultimate_osc_60m_VX
      - williams_r_60m_VX
      - adx_60m_VX
      - adx_pos_60m_VX
      - adx_neg_60m_VX
      - mass_index_60m_VX
      - macd_60m_VX
      - macd_diff_60m_VX
      - macd_signal_60m_VX
      - atr_60m_VX
      - bb_bbm_60m_VX
      - bb_bbh_60m_VX
      - bb_bbhi_60m_VX
      - bb_bbl_60m_VX
      - bb_bbli_60m_VX
      - sma_20_1mCL
      - sma_20_15mCL
      - sma_20_60mCL
      - rsi_1m_CL
      - tsi_1m_CL
      - ultimate_osc_1m_CL
      - williams_r_1m_CL
      - adx_1m_CL
      - adx_pos_1m_CL
      - adx_neg_1m_CL
      - mass_index_1m_CL
      - macd_1m_CL
      - macd_diff_1m_CL
      - macd_signal_1m_CL
      - atr_1m_CL
      - bb_bbm_1m_CL
      - bb_bbh_1m_CL
      - bb_bbhi_1m_CL
      - bb_bbl_1m_CL
      - bb_bbli_1m_CL
      - rsi_15m_CL
      - tsi_15m_CL
      - ultimate_osc_15m_CL
      - williams_r_15m_CL
      - adx_15m_CL
      - adx_pos_15m_CL
      - adx_neg_15m_CL
      - mass_index_15m_CL
      - macd_15m_CL
      - macd_diff_15m_CL
      - macd_signal_15m_CL
      - atr_15m_CL
      - bb_bbm_15m_CL
      - bb_bbh_15m_CL
      - bb_bbhi_15m_CL
      - bb_bbl_15m_CL
      - bb_bbli_15m_CL
      - rsi_60m_CL
      - tsi_60m_CL
      - ultimate_osc_60m_CL
      - williams_r_60m_CL
      - adx_60m_CL
      - adx_pos_60m_CL
      - adx_neg_60m_CL
      - mass_index_60m_CL
      - macd_60m_CL
      - macd_diff_60m_CL
      - macd_signal_60m_CL
      - atr_60m_CL
      - bb_bbm_60m_CL
      - bb_bbh_60m_CL
      - bb_bbhi_60m_CL
      - bb_bbl_60m_CL
      - bb_bbli_60m_CL
      - sma_20_1mGC
      - sma_20_15mGC
      - sma_20_60mGC
      - rsi_1m_GC
      - tsi_1m_GC
      - ultimate_osc_1m_GC
      - williams_r_1m_GC
      - adx_1m_GC
      - adx_pos_1m_GC
      - adx_neg_1m_GC
      - mass_index_1m_GC
      - macd_1m_GC
      - macd_diff_1m_GC
      - macd_signal_1m_GC
      - atr_1m_GC
      - bb_bbm_1m_GC
      - bb_bbh_1m_GC
      - bb_bbhi_1m_GC
      - bb_bbl_1m_GC
      - bb_bbli_1m_GC
      - rsi_15m_GC
      - tsi_15m_GC
      - ultimate_osc_15m_GC
      - williams_r_15m_GC
      - adx_15m_GC
      - adx_pos_15m_GC
      - adx_neg_15m_GC
      - mass_index_15m_GC
      - macd_15m_GC
      - macd_diff_15m_GC
      - macd_signal_15m_GC
      - atr_15m_GC
      - bb_bbm_15m_GC
      - bb_bbh_15m_GC
      - bb_bbhi_15m_GC
      - bb_bbl_15m_GC
      - bb_bbli_15m_GC
      - rsi_60m_GC
      - tsi_60m_GC
      - ultimate_osc_60m_GC
      - williams_r_60m_GC
      - adx_60m_GC
      - adx_pos_60m_GC
      - adx_neg_60m_GC
      - mass_index_60m_GC
      - macd_60m_GC
      - macd_diff_60m_GC
      - macd_signal_60m_GC
      - atr_60m_GC
      - bb_bbm_60m_GC
      - bb_bbh_60m_GC
      - bb_bbhi_60m_GC
      - bb_bbl_60m_GC
      - bb_bbli_60m_GC
      - sma_20_1mZN
      - sma_20_15mZN
      - sma_20_60mZN
      - rsi_1m_ZN
      - tsi_1m_ZN
      - ultimate_osc_1m_ZN
      - williams_r_1m_ZN
      - adx_1m_ZN
      - adx_pos_1m_ZN
      - adx_neg_1m_ZN
      - mass_index_1m_ZN
      - macd_1m_ZN
      - macd_diff_1m_ZN
      - macd_signal_1m_ZN
      - atr_1m_ZN
      - bb_bbm_1m_ZN
      - bb_bbh_1m_ZN
      - bb_bbhi_1m_ZN
      - bb_bbl_1m_ZN
      - bb_bbli_1m_ZN
      - rsi_15m_ZN
      - tsi_15m_ZN
      - ultimate_osc_15m_ZN
      - williams_r_15m_ZN
      - adx_15m_ZN
      - adx_pos_15m_ZN
      - adx_neg_15m_ZN
      - mass_index_15m_ZN
      - macd_15m_ZN
      - macd_diff_15m_ZN
      - macd_signal_15m_ZN
      - atr_15m_ZN
      - bb_bbm_15m_ZN
      - bb_bbh_15m_ZN
      - bb_bbhi_15m_ZN
      - bb_bbl_15m_ZN
      - bb_bbli_15m_ZN
      - rsi_60m_ZN
      - tsi_60m_ZN
      - ultimate_osc_60m_ZN
      - williams_r_60m_ZN
      - adx_60m_ZN
      - adx_pos_60m_ZN
      - adx_neg_60m_ZN
      - mass_index_60m_ZN
      - macd_60m_ZN
      - macd_diff_60m_ZN
      - macd_signal_60m_ZN
      - atr_60m_ZN
      - bb_bbm_60m_ZN
      - bb_bbh_60m_ZN
      - bb_bbhi_60m_ZN
      - bb_bbl_60m_ZN
      - bb_bbli_60m_ZN
      - sma_20_1mDX
      - sma_20_15mDX
      - sma_20_60mDX
      - rsi_1m_DX
      - tsi_1m_DX
      - ultimate_osc_1m_DX
      - williams_r_1m_DX
      - adx_1m_DX
      - adx_pos_1m_DX
      - adx_neg_1m_DX
      - mass_index_1m_DX
      - macd_1m_DX
      - macd_diff_1m_DX
      - macd_signal_1m_DX
      - atr_1m_DX
      - bb_bbm_1m_DX
      - bb_bbh_1m_DX
      - bb_bbhi_1m_DX
      - bb_bbl_1m_DX
      - bb_bbli_1m_DX
      - rsi_15m_DX
      - tsi_15m_DX
      - ultimate_osc_15m_DX
      - williams_r_15m_DX
      - adx_15m_DX
      - adx_pos_15m_DX
      - adx_neg_15m_DX
      - mass_index_15m_DX
      - macd_15m_DX
      - macd_diff_15m_DX
      - macd_signal_15m_DX
      - atr_15m_DX
      - bb_bbm_15m_DX
      - bb_bbh_15m_DX
      - bb_bbhi_15m_DX
      - bb_bbl_15m_DX
      - bb_bbli_15m_DX
      - rsi_60m_DX
      - tsi_60m_DX
      - ultimate_osc_60m_DX
      - williams_r_60m_DX
      - adx_60m_DX
      - adx_pos_60m_DX
      - adx_neg_60m_DX
      - mass_index_60m_DX
      - macd_60m_DX
      - macd_diff_60m_DX
      - macd_signal_60m_DX
      - atr_60m_DX
      - bb_bbm_60m_DX
      - bb_bbh_60m_DX
      - bb_bbhi_60m_DX
      - bb_bbl_60m_DX
      - bb_bbli_60m_DX
    timestamp_column: "timestamp"
    normalize_features: true

simulation:
  max_steps_per_episode: 1000
  warmup_steps: 0
  tick_size: 0.01
  initial_capital: 10000.0
  transaction_fee_pct: 0.0018
  slippage_model: "fixed"
  slippage_factor: 0.0001
  position_size_fixed_dollar: 10000.00
  allow_fractional_position_size: true
  pt_atr_mult: 200
  sl_atr_mult: 200
  live_plot: false
  random_start: false


agents:
  num_agents: 3
  shared_policy: true
  observation_space:
    type: "Box"
    low: -inf
    high: inf
    n_feats: 414
    n_stack: 1
  action_space:
    type: "Discrete"
    n: 4  # 0: hold 1: buy 2: sell, 3: close
  positions:
    max_position: 1
    min_position: -1


rl:
  algorithm: "PPO"
  policy_type: "MlpPolicy"
  learning_rate: 0.0003
  n_steps: 1024
  batch_size: 1024
  n_epochs: 1000
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  normalize_advantage: false
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: false
  sde_sample_freq: -1
  target_kl: null
  tensorboard_log: "./logs/"
  create_eval_env: true
  verbose: 1
  reward_type: simple_pnl #sortino_ratio
  device: cuda

backtesting:
  metrics:
    - "sharpe_ratio"
    - "sortino_ratio"
    - "max_drawdown"
    - "total_pnl"
    - "win_rate"
  results_dir: "./results"
  plot_results: true
